### ISSUE TITLE
Can't define project include paths for dependent libraries etc

### ISSUE THREAD

**Issue by ghost** [animatedb/oovaide#5]
I have a project that resides within a directory containing other projects that it depends on but also many more that it doesn't. I would like to be able to select just the project I want but also specify the paths for the other required projects i.e. include paths. Without  this I would have to analyze the entire codebase which may take a day or so!

**Comment by animatedb** [comment]
There are many ways to define projects in OovAide. The following shows an example directory structure.

RootDir
- ProjectToAnalyze
- Supplier1Project
  - Supplier1CodeDir1
  - Supplier1CodeDir2
- Supplier2Project

It sounds like the simplest in your case may be to select the ProjectToAnalyze as the Root Source Directory, then in the menu Analysis/Settings, in the C++ tab, add -I switches for the Supplier1Project and Supplier2Project directories.  In addition, there is a -ER switch, that allows
setting the Supplier1Project, and both of the code directories under it will be given to the compiler as -I switches.

Another method is to define the RootDir as the project, and then add exclude directories that will prevent certain directories from being analyzed.  Selecting the Analysis/Project Settings menu will display the Project Settings dialog.  This allows adding Exclude sub directories in the project under the root. Then it is possible to add include paths to the Analysis/Settings C++ settings using the standard -I switch or -ER switch.

A third approach is to define a package.  This does not add any more capability that the other options except that it may be easier to share setups with other people. This is likely not useful in your case.

I have recently improved the help for the Analysis/Settings Help button, so if you have more questions, that may help.  Let me know if the help can be improved.

If something is still too difficult for your project, please let me know.

**Comment by animatedb** [comment]
I think that the previous comment satisfies this request, but in addition, for version 16-2, there is a new build description for projects that is more advanced.
