### ISSUE TITLE
Win32 Release

### ISSUE THREAD

**Issue by ghost** [animatedb/oovaide#7]
Hello! 

Make pls release for windows platform.

Regards.

**Comment by animatedb** [comment]
I am curious why a new release is requested.  If it is for a new version of CLang, I am having difficulty supporting CLang versions after 3.7. After 3.7, CLang is using MSVC include paths and defines, so it doesn't appear to work well with mingw64's standard header files. The compile switch -fms-compatibility-version=19.00 gets rid of some errors, but there are still others.
I am also investigating using a new version of GTK in Windows, and I seem to be making progress on this.If I can get something working well, I will make a release, but it may take some time.

**Comment by animatedb** [comment]
A Windows release is now created using CLang 3.9.1 and using a new version of GTK. It turns out that there are different libclang.dll files for support of Mingw or for Visual Studio. The readme now describes this.
