### ISSUE TITLE
deb package not working

### ISSUE THREAD

**Issue by kikeenrique** [animatedb/oovaide#8]
Trying to execute binary oovaide raises dialog error:
$ oovaide 
**"Unable to find oovaideLayout.glade at /usr/local/share/oovaide/data/"**

It seems that compilation paths differ from debian package file paths.

$ dpkg -L oovaide 
/usr
/usr/local
/usr/local/bin
/usr/local/bin/ClangView
/usr/local/bin/OovEdit.css
/usr/local/bin/oovBuilder
/usr/local/bin/oovCMaker
/usr/local/bin/oovCovInstr
/usr/local/bin/oovCppParser
/usr/local/bin/oovEdit
/usr/local/bin/oovJavaParser.jar
/usr/local/bin/oovaide
/usr/local/bin/oovaide-allpkgs-win.txt
/usr/local/include
/usr/local/include/Oovaide
/usr/local/include/Oovaide/BuildConfigReader.h
/usr/local/include/Oovaide/BuildVariables.h
/usr/local/include/Oovaide/Builder.h
/usr/local/include/Oovaide/Components.h
/usr/local/include/Oovaide/CoverageHeaderReader.h
/usr/local/include/Oovaide/Debug.h
/usr/local/include/Oovaide/DirList.h
/usr/local/include/Oovaide/File.h
/usr/local/include/Oovaide/FilePath.h
/usr/local/include/Oovaide/Gui.h
/usr/local/include/Oovaide/IncludeMap.h
/usr/local/include/Oovaide/ModelObjects.h
/usr/local/include/Oovaide/NameValueFile.h
/usr/local/include/Oovaide/OovError.h
/usr/local/include/Oovaide/OovIpc.h
/usr/local/include/Oovaide/OovLibrary.h
/usr/local/include/Oovaide/OovProcess.h
/usr/local/include/Oovaide/OovProcessArgs.h
/usr/local/include/Oovaide/OovString.h
/usr/local/include/Oovaide/OovThreadedBackgroundQueue.h
/usr/local/include/Oovaide/OovThreadedWaitQueue.h
/usr/local/include/Oovaide/Options.h
/usr/local/include/Oovaide/Packages.h
/usr/local/include/Oovaide/Project.h
/usr/local/include/Oovaide/Version.h
/usr/local/lib
/usr/local/lib/CMake
/usr/local/lib/CMake/Oovaide
/usr/local/lib/CMake/Oovaide/OovaideConfig.cmake
/usr/local/lib/CMake/Oovaide/OovaideConfigVersion.cmake
/usr/local/lib/CMake/Oovaide/OovaideTargets-noconfig.cmake
/usr/local/lib/CMake/Oovaide/OovaideTargets.cmake
/usr/local/lib/liboovCommon.a
/usr/local/lib/liboovDbWriter.so
/usr/local/lib/liboovGuiCommon.a
/usr/share
/usr/share/oovaide
/usr/share/oovaide/data
/usr/share/oovaide/data/AnalyzeButton.png
/usr/share/oovaide/data/BinaryComponentsButton.png
/usr/share/oovaide/data/BuildButton.png
/usr/share/oovaide/data/ClassDiagramButton.png
/usr/share/oovaide/data/IncludeDiagramButton.png
/usr/share/oovaide/data/OovEditLogo.png
/usr/share/oovaide/data/OovLogo.png
/usr/share/oovaide/data/OperationDiagramButton.png
/usr/share/oovaide/data/PortionDiagramButton.png
/usr/share/oovaide/data/StepIntoButton.png
/usr/share/oovaide/data/StepOverButton.png
/usr/share/oovaide/data/ZoneDiagramButton.png
/usr/share/oovaide/data/oovEdit.glade
/usr/share/oovaide/data/oovaideLayout.glade
/usr/share/oovaide/doc
/usr/share/oovaide/doc/userguide
/usr/share/oovaide/doc/userguide/CLangViewHelp.html
/usr/share/oovaide/doc/userguide/Example1Classes.oov
/usr/share/oovaide/doc/userguide/Example1Classes.svg
/usr/share/oovaide/doc/userguide/Example1Portion.oov
/usr/share/oovaide/doc/userguide/Example1Portion.svg
/usr/share/oovaide/doc/userguide/Example1Seq.svg
/usr/share/oovaide/doc/userguide/Example2Classes.oov
/usr/share/oovaide/doc/userguide/Example2Classes.svg
/usr/share/oovaide/doc/userguide/Example2Comps.svg
/usr/share/oovaide/doc/userguide/Example2Seq.svg
/usr/share/oovaide/doc/userguide/Example3Classes.oov
/usr/share/oovaide/doc/userguide/Example3Classes.svg
/usr/share/oovaide/doc/userguide/Example3Comps-linux.svg
/usr/share/oovaide/doc/userguide/Example3Comps.svg
/usr/share/oovaide/doc/userguide/Example3Seq.svg
/usr/share/oovaide/doc/userguide/ExampleNamesClasses.oov
/usr/share/oovaide/doc/userguide/ExampleNamesClasses.svg
/usr/share/oovaide/doc/userguide/ExampleSourceTree.svg
/usr/share/oovaide/doc/userguide/OovLogo.svg
/usr/share/oovaide/doc/userguide/examples.html
/usr/share/oovaide/doc/userguide/oovaidebuildhelp.html
/usr/share/oovaide/doc/userguide/oovaideuserguide.html

**Comment by emilio-millan** [comment]
I'm seeing the same thing.

**Comment by animatedb** [comment]
The 17-5 release fixes the .deb problem by loading files from /usr/share/oovaide.
